---
title: "**Pelagics**"
subtitle: "Operating Model Simple Forecasts"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
mathjax: TRUE
fig_width: 6 
fig_height: 4 
tags: FLR FLCore introduction
license: Creative Commons Attribution-ShareAlike 4.0 International Public License
bibliography: /home/laurie/Desktop/refs.bib
---

```{r, knitr, eval=TRUE, echo=FALSE, warning=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)

opts_chunk$set(cache     =TRUE, 
               comment   =NA, 
               warning   =FALSE, 
               message   =FALSE, 
               error     =FALSE, 
               echo      =FALSE, 
               eval      =TRUE,cache   =TRUE,
               cache.path="../cache/forecast/",
               fig.path  ="../tex/figs/forecast/",
               fig.width =8,
               fig.height=6,
               dev       ="png")

iFig=0
iTab=0
```

```{r, pkgs}
library(FLCore)
library(ggplotFL)
library(FLfse)
library(FLBRP)
library(FLasher)
library(FLSAM)
library(kobe)

library(TMB)
library(stockassessment)
  
library(plyr)
library(reshape)
library(magrittr)
  
library(grid)

library(compositions)

theme_set(theme_bw(16))
```


```{r, dbox}
source('../R/get_dropbox.r')

dropboxdir<-try(file.path(get_dropbox(), "pelagics"))

if ("try-error"%in%is(dropboxdir))
  dropboxdir="~/Dropbox/pelagics"
```


```{r}
load(file.path(dropboxdir,"data/inputs/ices.RData"))
load(file.path(dropboxdir,"data/om/whb.RData"))
load(file.path(dropboxdir,"data/om/her.RData"))
load(file.path(dropboxdir,"data/om/mac.RData"))
refs=read.csv(file.path(dropboxdir,"data/inputs/refs.csv"),header=T)

prj<-function(x,fmsy,yrs=2001:2021,nit=100){
  f0=array(c(rep(c(1,rep(0,dim(x)[1])),dim(x)[1]-1),1),c(dim(harvest(x))[1],dim(harvest(x))[1]),
           dimnames=list(dims(x)$min:dims(x)$max,dims(x)$min:dims(x)$max))
  f0=f0*0.05
  F0=aperm(maply(data.frame(year=yrs), function(year) rlnorm.rplus(100,rep(0,dim(x)[1]),f0)),c(3,1,2)) 
  names(dimnames(F0))[c(1,3)]=c("age","iter")
  F0=as.FLQuant(c(F0),dimnames=dimnames(F0))
  
  x=propagate(x,nit)
  stock.n(x)[,ac(yrs)]=stock.n(x)[,ac(yrs)]%*%F0
  
  control  =window(fbar(x),start=min(yrs))%=%fmsy
  control=as(FLQuants("f"=control),"fwdControl")
  
  res=fwd(x,sr=rec(x),control=control)
  res}

whbFwd=prj(whb,attributes(ices[["whb.27.1-91214"]])$benchmark$Fmsy)
save(whbFwd,file=file.path(dropboxdir,"data/om/whbFwd.RData"))

herFwd=prj(her,attributes(ices[["her.27.3a47d"]])$benchmark$Fmsy)
save(herFwd,file=file.path(dropboxdir,"data/om/herFwd.RData"))

macFwd=prj(mac,attributes(ices[["mac.27.nea"]])$benchmark$Fmsy)
save(macFwd,file=file.path(dropboxdir,"data/om/macFwd.RData"))
```


```{r}
ggplot(melt(refs[,c("spp","assessmentyear","flim","fpa","fmsy")],id.vars=c("spp","assessmentyear")))+
  geom_point(aes(assessmentyear,as.numeric(value),colour=variable))+
  facet_grid(spp~.,scale="free")+
  xlab("Year")+ylab("F")
```

```{r}
ggplot(melt(refs[,c("spp","assessmentyear","blim","bpa","msybtrigger")],id.vars=c("spp","assessmentyear")))+
  geom_point(aes(assessmentyear,as.numeric(value),colour=variable))+
  facet_grid(spp~.,scale="free")+
  xlab("Year")+ylab("SSB")
```

```{r}
plot(window(whbFwd,start=1990))+
  theme_bw()+
  theme(legend.position="none")
```

**Figure `r iFig=iFig+1; iFig`** Blue whiting: simple projection. 

```{r}
load(file=file.path(dropboxdir,"data/inputs/HER/NSAS_HAWG2022_sf_retro.RData"))

plot(window(herFwd,start=1990))+
  theme_bw()+
  theme(legend.position="none")
```

**Figure `r iFig=iFig+1; iFig`** Herring: simple projection. 

```{r}
plot(window(macFwd,start=1990))+
  theme_bw()+
  theme(legend.position="none")
```

**Figure `r iFig=iFig+1; iFig`** Mackerel: simple projection. load(file=file.path(dropboxdir,"data/om/her.RData")


```{r, whbErr}
load(file=file.path(dropboxdir,"data/om/whbRet.RData"))

om1=whbRet[[1]]
whbErr=laply(whbRet, function(x){
  yr=ac(dims(fbar(x))$maxyear)
  
  c(f  =c(fbar(x)[,yr]/fbar(om1)[,yr]),
    ssb=c(ssb(x)[,yr])/c(ssb(om1)[,yr]))})

save(whbErr, file=file.path(dropboxdir,"data/om/whbErr.RData"))
```

# Funding

# References
